baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'PRANA'

theme = "hugo-theme-nix"

[params]
  Name = "Prajul"
  CopyRightName = "Prajul Nambiar"
  HeaderSitename = "PRANA"
  HeaderSiteLogo = "https://i.postimg.cc/ryQXbLJn/My-Trademark.png"
  About = "Enterprise Technical Architect | Site Reliability Engineer | Observability | DevOps | Cloud | Microservices"
  CvURL = "/Resume.pdf"
  ProfilePicture = "https://i.postimg.cc/PJcWSyQD/gadsarlake-prajul.jpg"
  Email = "prajul.nambiar@outlook.com"
  GithubID = "prajul-nambiar"
  LinkedInID = "prajul-p-nambiar"
  TwitterID = "prajul_nambiar"
  
[menu]
  [[menu.header]]
    # identifier = "Resume"
    # name = "Resume"
    # #weight = 0
    # url = "/Resume"

  # [[menu.header]]
  #   identifier = "post"
  #   name = "Posts"
  #   weight = 0
  # [[menu.header]]
  #   parent = "post"
  #   name = "All Posts"
  #   url = "/posts"
  # [[menu.header]]
  #   parent = "post"
  #   name = "categories"
  #   url = "/categories"
  # [[menu.header]]
  #   parent = "post"
  #   name = "tags"
  #   url = "/tags"

